# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vitals.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'vitals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvitals.proto\x12\rbr.tcc.vitals\"Y\n\rBloodPressure\x12\x15\n\x08systolic\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x16\n\tdiastolic\x18\x02 \x01(\x02H\x01\x88\x01\x01\x42\x0b\n\t_systolicB\x0c\n\n_diastolic\"\xf7\x01\n\tVitalSign\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x13\n\x0bsignal_type\x18\x02 \x01(\t\x12\x16\n\x0cscalar_value\x18\x03 \x01(\x02H\x00\x12*\n\x02\x62p\x18\x04 \x01(\x0b\x32\x1c.br.tcc.vitals.BloodPressureH\x00\x12\x14\n\x0ctimestamp_ms\x18\x05 \x01(\x03\x12\x16\n\x0eschema_version\x18\x06 \x01(\t\x12\x18\n\x10pipeline_version\x18\x07 \x01(\t\x12\x13\n\x0bscenario_id\x18\x08 \x01(\t\x12\x17\n\x0fonset_offset_ms\x18\t \x01(\x03\x42\x07\n\x05value\"\x8f\x01\n\nAlertEvent\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\t\x12\x13\n\x0bnews2_score\x18\x03 \x01(\x05\x12\x14\n\x0ctimestamp_ms\x18\x04 \x01(\x03\x12\x16\n\x0eschema_version\x18\x05 \x01(\t\x12\x18\n\x10pipeline_version\x18\x06 \x01(\t\"\xb9\x02\n\x12\x44\x65\x61\x64LetterEnvelope\x12\x18\n\x10original_payload\x18\x01 \x01(\x0c\x12\x12\n\nerror_type\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x16\n\x0esource_subject\x18\x04 \x01(\t\x12\x16\n\x0erejected_at_ms\x18\x05 \x01(\x03\x12\x16\n\x0eschema_version\x18\x06 \x01(\t\x12\x18\n\x10pipeline_version\x18\x07 \x01(\t\x12\x18\n\x10source_transport\x18\x08 \x01(\t\x12\x14\n\x0csource_topic\x18\t \x01(\t\x12\x18\n\x10source_partition\x18\n \x01(\x05\x12\x15\n\rsource_offset\x18\x0b \x01(\x03\x12\x1b\n\x13source_timestamp_ms\x18\x0c \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vitals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOODPRESSURE']._serialized_start=31
  _globals['_BLOODPRESSURE']._serialized_end=120
  _globals['_VITALSIGN']._serialized_start=123
  _globals['_VITALSIGN']._serialized_end=370
  _globals['_ALERTEVENT']._serialized_start=373
  _globals['_ALERTEVENT']._serialized_end=516
  _globals['_DEADLETTERENVELOPE']._serialized_start=519
  _globals['_DEADLETTERENVELOPE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
